#!/usr/bin/env python

### If you get the error bellow, that means you have forgotten to activate the appropariate virtualenv
### $ python query-nba 
# Traceback (most recent call last):
#   File "query-nba", line 4, in <module>
#     import metapy
### HOW TO FIX: cd ; source env/search-nba/bin/activate ; cd - ;

import sys
import metapy

query = unicode(sys.argv[1], 'utf-8')

print "QUERY: %s" % query

idx = metapy.index.make_inverted_index('nba.toml')
print("CORPUS: num_docs={} unique_terms={} avg_doc_length={}".format( idx.num_docs(),idx.unique_terms(),idx.avg_doc_length()))

ranker = metapy.index.OkapiBM25()
query_doc = metapy.index.Document()
query_doc.content("Chicago Bulls Champions")
top_docs = ranker.score(idx, query_doc, num_results=10)

for num, (d_id, _) in enumerate(top_docs):
    url = idx.metadata(d_id).get('url')
    md5 = idx.metadata(d_id).get('md5_url')
    print("{}: {}\n{}".format(num + 1, md5, url))
