#!/usr/bin/env python

import sys
import metapy

query = unicode(sys.argv[1], 'utf-8')

print "QUERY: %s" % query

idx = metapy.index.make_inverted_index('nba.toml')
print("CORPUS: num_docs={} unique_terms={} avg_doc_length={}".format( idx.num_docs(),idx.unique_terms(),idx.avg_doc_length()))

ranker = metapy.index.OkapiBM25()
query_doc = metapy.index.Document()
query_doc.content(query)
top_docs = ranker.score(idx, query_doc, num_results=10)

for num, (d_id, _) in enumerate(top_docs):
    url = idx.metadata(d_id).get('url')
    md5 = idx.metadata(d_id).get('md5_url')
    print("{}: {} score\n{}".format(num + 1, md5, url))
